name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  # Or the branch you are using

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      RASPBERRY_SSH_PRIVATE_KEY: ${{ secrets.RASPBERRY_SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          echo "$RASPBERRY_SSH_PRIVATE_KEY" | base64 --decode > private_key
          chmod 600 private_key
          eval $(ssh-agent -s)
          ssh-add private_key

      - name: Debug SSH Agent
        run: ssh-add -l || echo "No SSH keys added"


      - name: Deploy to Raspberry Pi
        run: |
          ssh -o StrictHostKeyChecking=no millan@millancastro.ddns.net << 'EOF'
            cd /home/millan/MillanCastroWebsite || exit
            git pull || exit
            npm install || exit
            npm run build || exit
            pm2 restart all || exit
          EOF
